// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY0dPEFjUrHrJKs_dJNmpIJkJyYYnaUvQ',
    appId: '1:566971443602:web:0776f913a12c6e1746794b',
    messagingSenderId: '566971443602',
    projectId: 'piggu-23f92',
    authDomain: 'piggu-23f92.firebaseapp.com',
    storageBucket: 'piggu-23f92.appspot.com',
    measurementId: 'G-XW8PHLL56H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkqKOnvflKsv3VUxOiUcCaBJa2GDE4inU',
    appId: '1:566971443602:android:a8be5d82a3cd126546794b',
    messagingSenderId: '566971443602',
    projectId: 'piggu-23f92',
    storageBucket: 'piggu-23f92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7OyI7DMtXTx0Lt2sMt_WiNrhQMyF1U0',
    appId: '1:566971443602:ios:31a88c76f2c319ed46794b',
    messagingSenderId: '566971443602',
    projectId: 'piggu-23f92',
    storageBucket: 'piggu-23f92.appspot.com',
    iosBundleId: 'com.example.piggu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7OyI7DMtXTx0Lt2sMt_WiNrhQMyF1U0',
    appId: '1:566971443602:ios:31a88c76f2c319ed46794b',
    messagingSenderId: '566971443602',
    projectId: 'piggu-23f92',
    storageBucket: 'piggu-23f92.appspot.com',
    iosBundleId: 'com.example.piggu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY0dPEFjUrHrJKs_dJNmpIJkJyYYnaUvQ',
    appId: '1:566971443602:web:392a932ee7b1d93746794b',
    messagingSenderId: '566971443602',
    projectId: 'piggu-23f92',
    authDomain: 'piggu-23f92.firebaseapp.com',
    storageBucket: 'piggu-23f92.appspot.com',
    measurementId: 'G-4QB5VBH22Q',
  );
}
