# Generated by Django 5.1.3 on 2024-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
