# Generated by Django 5.1.3 on 2024-11-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='piggu_expense',
        ),
        migrations.AlterModelTable(
            name='income',
            table='piggu_income',
        ),
    ]
