# Generated by Django 5.1.3 on 2024-11-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0002_rename_date_expense_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
