# Generated by Django 5.1.3 on 2024-11-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firebase_uid',
            new_name='user_id',
        ),
    ]
