# Generated by Django 5.1.3 on 2024-11-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='category',
            new_name='source',
        ),
    ]
