# Generated by Django 5.1.3 on 2024-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0004_rename_firebase_uid_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='user_id',
            field=models.CharField(default='placeholder_user', max_length=128),
            preserve_default=False,
        ),
    ]
