# Generated by Django 5.1.3 on 2024-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0005_receipt_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='merchant_name',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='receipt',
            name='source',
            field=models.CharField(default='Others', max_length=100),
        ),
    ]
