# Generated by Django 5.1.3 on 2024-11-25 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggu', '0006_rename_total_amount_receipt_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='merchant',
            new_name='merchant_name',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='timestamp',
            new_name='receipt_date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='source',
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
